### ISSUE TITLE
v-update-letsencrypt-ssl cannot update when some domains are suspended.

### ISSUE THREAD

**Issue by crackdepirate** [serghey-rodin/vesta#1180]
### Operating System (OS/VERSION):

Linux five.xxxxxxxxxxx.ca 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 

### VestaCP Version:
vesta
core package	
Version:0.9.8 (amd64)

### Installed Software (what you got with the installer):
php-fpm, nginx, mysql

### Steps to Reproduce:

1. suspend a domain,
2. wait to have an expired ssl certificate
3. run "sudo /usr/local/vesta/bin/v-update-letsencrypt-ssl"

### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?f=19&t=12617
at this time, I've updated with the command line "generate_ssl [user] [domain]" 
it works like a charm. 

### Other Notes:

Anything else?

hello, 
the cronjob : 
sudo /usr/local/vesta/bin/v-update-letsencrypt-ssl
won't renew ssl on active domain when others are suspended. 

log:
sudo /usr/local/vesta/bin/v-update-letsencrypt-ssl

root@five:~# /usr/local/vesta/bin/v-update-letsencrypt-ssl
Error: Invalid response from http://five.xxxxxxxxxxxxxx.ca/.well-known/acme-challenge/654Qps8Pj8cS92yvI22-VIo2gityzhM4UZLVxvLbJSM: \
Error: Invalid response from http://xxxxxxxxxxxxxxxx.ca/.well-known/acme-challenge/BT30rXwqJodCu6lXjrAMzGkt-SYms4Zya1PmfMGj67c [159.203.14.175]: 404
Error: web 643.xxxxxxxxx.ca is suspended
Error: web staging.xxxxxxx.ca is suspended
root@five:~#

**Comment by molny** [comment]
For a long time I receive letters every night with errors.
Almost two years have passed, but the problem has not been solved. 😡🔥

**Comment by fsoyer** [comment]
In fact, this issue was solved by @skullwritter in [2018](https://github.com/serghey-rodin/vesta/issues/1731).  I don't understand why I have this error on a version 0.9.8-26 from 2019-10-02 ?? This fix was not already included since 0.9.8-24 ?

**Comment by Lupul** [comment]
@fsoyer the fix pushed by skullwriter was reverted after a while in https://github.com/serghey-rodin/vesta/commit/f8b4d42b740752e17944370440f37d3105f4b21f

**Comment by fsoyer** [comment]
Well, I see, but do you know what was the reason ? Does it cause another bug ? It's annoying to have this messages all days...

**Comment by skullwritter** [comment]
@fsoyer dunno, i gave a solution, they could have created a workaround if there was a bug...

**Comment by fsoyer** [comment]
I can confirm that in the last version I updated - 0.9.26 - this was not resolved.
I've manually added your code and the problem was solved. But it's necessary temporary :/
