### ISSUE TITLE
No work button "open webmail", no open rouncube... open url with port.

### ISSUE THREAD

**Issue by skorpions2000** [serghey-rodin/vesta#2095]
**Operating System (OS/VERSION):**

Debian 9.13

**VestaCP Version:**

Version: 1.0.0 (Amd64) Release: 2

**Installed Software (what you got with the installer):**

vesta(Core Package)
vesta-php(Php Interpreter)
vesta-nginx(Internal Web Server)
vesta-ioncube(Php Encoder)
vesta-softaculous(App Installer)

**Bug?/Problem:**

After click MAIL -> LIST ACCOUNT (on chose domen)
No work button "open webmail", no open rouncube... open url with port, please how delete port from url....
![02](https://user-images.githubusercontent.com/11683786/139585596-4bd7d5b8-b87b-40e3-baa0-a7c14e18a5e9.jpg)
![03](https://user-images.githubusercontent.com/11683786/139585610-bd59c1c0-024e-4b32-bdb8-ca0eb9328c87.jpg)

**Comment by anton-reutov** [comment]
Try to open without port 8083

**Comment by skorpions2000** [comment]
> Try to open without port 8083

yes, when delete port rouncube normal opening, but in button link generate with port.

**Comment by anton-reutov** [comment]
Ok, we will fix it

**Comment by hollanddata** [comment]
Link goes to https://ns.domain.netnull/ when Webmail URL is set manually.

**Comment by anton-reutov** [comment]
How you set manual link for webmail?

**Comment by hollanddata** [comment]
Server / Configure / MAIL / Webmail URL

**Comment by anton-reutov** [comment]
1.0.0.3 1.0.0.4 - should be working
for ex.. try this

`/mail`

**Comment by hollanddata** [comment]
I updated but still the same /null/

**Comment by anton-reutov** [comment]
Can you provide access to your server, we will check this
info@vestacp.com

**Comment by hollanddata** [comment]
URL is still incorrect. It shows the correct url but opens incorrect. The server url and link are combined.

![2021-11-24 20_36_13-Window](https://user-images.githubusercontent.com/54579231/143303477-1afacc9a-1336-4b98-a879-401e8d8ab275.png)

![2021-11-24 20_38_55-Window](https://user-images.githubusercontent.com/54579231/143303518-a82f5eb3-b595-4733-b4d6-53f40fc770c6.png)
